# -*- coding: utf-8 -*-
"""exp3 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bvWsDvhhA3svC94JlRI1wlrRAkSsQoyx
"""

a=12
print(id(a))
b=a
print(id(b))
a=13
print(id(a))

a = [1, 2, 3, 4, 5] # List of integers
b = ['apple', 'banana', 'cherry'] # List of strings
c = [1, 'hello', 3.14, True] # Mixed data types
print(a)
print(b)
print(c)

[1, 2, 3, 4, 5]
['apple', 'banana', 'cherry']
[1, 'hello', 3.14, True]

a = [10, 20, "GfG", 40, True]
print(a)
print(a[0])
print(a[1])
print(a[2])

a = list((1, 2, 3, 'apple', 4.5))
print(a)
b = list("MIT")
print(b)

a = [2] * 5
b = [0] * 7
print(a)
print(b)

a = [10, 20, 30, 40, 50]
print(a[0])
print(a[4])
print(a[-1])
print(a[1:4])

a = []
a.append(10)
print("After append(10):", a)
a.insert(0, 5)
print("After insert(1, 5):", a)
a.extend([15, 20, 25])
print("After extend([15, 20, 25]):", a)
a.clear()
print("After clear():", a)

a = []
for i in range(5):
 a.append(i)
print(a)

list1 = [1, 2, 3]
list2 = [4, 5, 6]
list1=list1+list2
print(list1)

list1 = [ 1, 2, 3, 4, 5, 6 ]
num_tuple = (4, 5, 6)
list1.insert(2, num_tuple)
print(list1)
print(list1[2][1])

fruits = ['apple', 'banana', 'cherry']
fruits.insert(2, 'orange')
print(fruits)

list1 = [1, 2, 3]
s= {4,5,6}
list1.insert(3,s)
print(list1)

a = [10, 20, 30, 40, 50]
a[1] = 25
print(a)

a = [10, 20, 30, 40, 50,30]
a.remove(30)
print("After remove(30):", a)

a = [10, 20, 30, 40, 50]
popped_val = a.pop()
print("Popped element:", popped_val)
print("After pop(1):", a)

a = [10, 20, 30, 40, 50]
popped_val = a.pop()
print("Popped element:", popped_val)
print("After pop(1):", a)

a = [10, 20, 30, 40, 50]
del a[0]
print("After del a[0]:", a)

a = [10, 20, 30, 40, 50, 60, 70]
del a[1:4]
print(a)

a = list()
b = list((1, 2, 3))
c = list("GfG")
print(a, type(a))
print(b, type(a))
print(c, type(a))

a = list(range(3))
print(a)
# Convert a comprehension to list
b = list(x * x for x in range(5))
print(b)

matrix = [ [1, 2, 3],
[4, 5, 6],
[7, 8, 9] ]
print(matrix[1])
print(matrix[1][2])

squares = [x**2 for x in range(1, 6)]
print(squares)

a,b,c=map(int, input("Enter value for a,b,c:-").split())
numbers = [a, b, c]
greatest = [x for x in numbers if x >= a and x >= b and x >= c][0]
print("The greatest number is:", greatest)

a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print(a[1:4])

a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print(a[::])
print(a[:])

a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
b = a[2:]
print(b)

c = a[:3]
print(c)

a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
b = a[::2]
print(b)

c = a[1:8:3]
print(c)

a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
b = a[-2:]
print(b)

c = a[0:6]
print(c)

a=[1,2,3,4,5,6,7,8,9]
d = a[-4:-1]
print(d)

a=[1,2,3,4,5,6,7,8,9]
e = a[-8:-1:2]
print(e)

a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print(a[::-1])

t1 = (1, 2, 3, 4,5,6,7)
*a, b, c = t1
print(f"Original tuple: {t1}")
print(f"Unpacked variables: a={a}, b={b}, c={c}")

a = [1, 3, 5, 7, 9]
for i, x in enumerate(a):
  print(i, x)

a = [1, 3, 5, 7, 9]
i = 0
while i < len(a):
    print(a[i])
    i += 1

a = [1, 3, 5, 7, 9]
print(len(a))
print("\n")
for i in range(len(a)):
     print(a[i])

print("MIT", "WPU", "PUNE", sep="\n")

print("MIT " , end="")
print("WPU")

a = [1, 2, 3, 2]
print(a.count(2))

a = [1, 2, 3]
a.reverse()
print(a)

a = [3, 1, 2]
a.sort()
print(a)
a.sort(reverse=True)
print(a)

prices = [159.54, 37.13, 71.17]
price_max = max(prices)
print(price_max)

months = ['January', 'February', 'March']
prices = [238.11, 237.81, 238.91]
min_price = min(prices)
print(min_price)
min_index = prices.index(min_price)
print(min_index)
min_month = months[min_index]
print(min_month)

empty_tuple = ()
print("Empty Tuple:", empty_tuple)
numbers = (10, 20, 30, 40)
print("Numbers Tuple:", numbers)

mixed = (10, "Hello", 3.14, True)
print("Mixed Tuple:", mixed)
nested = (1, 2, (3, 4, 5))
print("Nested Tuple:", nested)

implicit_tuple = 1, 2, 3, 4
print("Tuple without parentheses:", implicit_tuple)

single = (10,)
print(type(single))
print("Single Element Tuple:", single)
print()

t1 = (1, 2, 3)
t2 = (4, 5, 6)
combined = t1 + t2
print("Concatenated Tuple:", combined)

repeated = t1 * 2
print("Repeated Tuple:", repeated)

print("Length of tuple:", len(t1))
print()

colors = ("red", "green", "blue", "yellow", "purple")
print("First element:", colors[0])
print("Third element:", colors[2])
print("Last element:", colors[-1])

colors = ("red", "green", "blue", "yellow", "purple")
print("Colors[0:3]:", colors[0:3])
print("Colors[2:]:", colors[2:])
print("Colors[:4]:", colors[:4])
print("Colors[-3:]:", colors[-3:])
print()

nums = (15, 8, 22, 5, 13, 30)
print("Tuple:", nums)
print("Length:", len(nums))
print("Maximum:", max(nums))
print("Minimum:", min(nums))
print("Sum:", sum(nums))
print("Sorted (as list):", sorted(nums))
t = (1, 2, 3, 4, 5)

tuple_data = (1, 2, 3, 4)
list_data = list(tuple_data)
print("Tuple to List:", list_data)

list_data.append(5)
print("Modified List:", list_data)

tuple_data = tuple(list_data)
print("List back to Tuple:", tuple_data)
print()