# -*- coding: utf-8 -*-
"""exp2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bHY2dQHzkRqzTdvcP4mqkKDnSKM8rD7R
"""

number = int(input('Enter a number: '))
if number > 0:
  print('number is positive number.')
else:
  print('number is a negative number.')

number = -5
if number > 0:
  print('Positive number')
elif number < 0:
  print('Negative number')
else:
  print('Zero')
print('This statement is always executed')

score = int(input("Enter the student's score: "))
if score >= 90:
print("Grade: A")
elif score >= 80:
print("Grade: B")
elif score >= 70:
print("Grade: C")
elif score >= 60:
print("Grade: D")
else:
print("Grade: F")

a, b = 10, 20
if a < 50:
  if b < 100:
print("a is less than 50 and b is less than 100")
else:
print("a is less than 50 but b is not less than 100")
else:
print("a is not less than 50")

num1 = int(input("Enter first number: "))
num2 = float(input("Enter second number: "))
num3 = float(input("Enter third number: "))
if (num1 >= num2) and (num1 >= num3):
largest = num1
elif (num2 >= num1) and (num2 >= num3):
largest = num2
else:
largest = num3
print("The largest number is", largest)

num = int(input("Enter a number: "))
if num > 0:
print("Positive number")
elif num == 0:
print("Zero")
else:
print("Negative number")

num = int(input("Enter a number: "))
if (num % 2) == 0:
print("{0} is Even".format(num))
else:
print("{0} is Odd".format(num))

for i in range(0, 4):
print(i)

for i in range(1, 4):
print(i)

for i in range(0, 10,2):
print(i)

for i in range(1, 10,2):
print(i)

n = int(input("Enter a number"))
for i in range(0, n):
print(i)

list1 = ['MIT', 'WPU', 'Pune']
for i in list1:
print(i)

list1 = ['MIT', 'WPU', 'Pune']
for i in list1:
if i == 'Pune':
break
print(i)

list1 = ['MIT', 'WPU', 'Pune','India']
for i in list1:
if i == 'Pune':
continue
print(i)

for i in range(5):
if i == 3:
break
print(i)

for i in range(5):
if i == 3:
continue
print(i)

n = 10
# use pass inside if statement
if n > 10:
pass
print('Hello')

x = 10
if x > 5:
pass# Code will be added later
else:
print("x is 5 or less")
